### PR TITLE
Add default behavior options

### PR DESCRIPTION
**Pull request by JorgenPhi**

### CODE REVIEW

**Comment by clod81** [comment]
Thanks for the PR.
I tried on latest Chrome against https://mdn.github.io/sw-test/ but even I choose Allow as default, I see the registration of the SW is disallowed?

**Comment by JorgenPhi** [comment]
Hmm perhaps it needs to be reloaded or something after changing the setting. Let me do a little more work on it.

**Comment by JorgenPhi** [comment]
For me, it seems like the dropdown option is working on https://gauntface.github.io/simple-push-demo/

Do note that you need to delete the domain entry before refreshing for it to allow, ask, or block by default.

For the MDN test, it seems like it's being caught by the `Prevent registration by default.` line, which would cause a prompt to not appear in the current release version or my fork. This can be seen by the error messages in the console for the window.

Not sure if this is something that could be easily fixed.

**Comment by clod81** [comment]
Looks better on that test example. One thing: when I select block default, clear the history of sites blocked or allowed, then set allow by default, the first time I load the page it blocks the registration. Only the second time I reload the same page the SW is registered

**Pull request closed without merging**
